name: scandit_flutter_datacapture_price_label
description: This plugin nables Price Label Verification capabilities.
version: 8.0.0
homepage: https://scandit.com

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: 6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.scandit.datacapture.flutter.price_label
        pluginClass: ScanditFlutterDataCapturePriceLabelPlugin
      ios:
        pluginClass: ScanditFlutterDataCapturePriceLabelPlugin
